//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthDiagnosticTool.ProductManager.Config {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class ProductIniFileSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProductIniFileSetting defaultInstance = ((ProductIniFileSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProductIniFileSetting())));
        
        public static ProductIniFileSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UDS")]
        public string SectionName_UDS {
            get {
                return ((string)(this["SectionName_UDS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("diagnosticLayerParamsFile")]
        public string SectionKeyName_UDS_diagnosticLayerParamsFile {
            get {
                return ((string)(this["SectionKeyName_UDS_diagnosticLayerParamsFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("diagnosticLayerParams.json")]
        public string SectionKeyValue_UDS_diagnosticLayerParamsFile {
            get {
                return ((string)(this["SectionKeyValue_UDS_diagnosticLayerParamsFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("product.ini")]
        public string ProductIniFileName {
            get {
                return ((string)(this["ProductIniFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transportLayerParamsFile")]
        public string SectionKeyName_UDS_transportLayerParamsFile {
            get {
                return ((string)(this["SectionKeyName_UDS_transportLayerParamsFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transportLayerParams.json")]
        public string SectionKeyValue_UDS_transportLayerParamsFile {
            get {
                return ((string)(this["SectionKeyValue_UDS_transportLayerParamsFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("readDidButtonsConfigFile")]
        public string SectionKeyName_UDS_readDidButtonsConfigFile {
            get {
                return ((string)(this["SectionKeyName_UDS_readDidButtonsConfigFile"]));
            }
            set {
                this["SectionKeyName_UDS_readDidButtonsConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("readDidButtonsConfig.csv")]
        public string SectionKeyValue_UDS_readDidButtonsConfigFile {
            get {
                return ((string)(this["SectionKeyValue_UDS_readDidButtonsConfigFile"]));
            }
            set {
                this["SectionKeyValue_UDS_readDidButtonsConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("writeDidButtonsConfigFile")]
        public string SectionKeyName_UDS_writeDidButtonsConfigFile {
            get {
                return ((string)(this["SectionKeyName_UDS_writeDidButtonsConfigFile"]));
            }
            set {
                this["SectionKeyName_UDS_writeDidButtonsConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("writeDidButtonsConfigFile.csv")]
        public string SectionKeyValue_UDS_writeDidButtonsConfigFile {
            get {
                return ((string)(this["SectionKeyValue_UDS_writeDidButtonsConfigFile"]));
            }
            set {
                this["SectionKeyValue_UDS_writeDidButtonsConfigFile"] = value;
            }
        }
    }
}
